
import {EQUIPMENT,BUILD_MENU_ORDER} from '../../content/equipment';
import {RESEARCH,RESEARCH_BRANCHES,type ResearchId} from '../../content/research';
import {CAPABILITY_INFO} from '../../content/scenario';
import type {GameSimulation} from '../../simulation/GameSimulation';
import type {GameSnapshot,EquipmentKind,StaffMember,CapabilityId} from '../../simulation/types';
import {taskLabel} from '../../simulation/operations';
import {SITE_ICONS} from '../../game/siteArt';
import {PORTRAITS} from './portraits';
import {PRODUCT,ROLES,solarEstimate,researchSupport,remainingResearch,capabilityOffer,staffDestination,traitText} from './data';
import {esc,money,percent,action,glyph,heading,stat,meter,tag,empty} from './components';

export function procurement(s:GameSnapshot,category:string,selected:EquipmentKind,compare:boolean):string{
 const items=BUILD_MENU_ORDER.filter(id=>PRODUCT[id].group===category),d=EQUIPMENT[selected],p=PRODUCT[selected],solar=selected.includes('pv'),estimate=solarEstimate(selected,s);
 const blocked=selected==='workshop'&&!s.capabilities.includes('radio_dispatch')?'First complete a manual repair':s.cash<d.cost?'You need '+money(d.cost-s.cash)+' more':null;
 const compareTable='<table class="mv-compare"><caption>Same footprint. Different operating strategy.</caption><thead><tr><th scope="col">Your decision</th><th scope="col">Sun-ish</th><th scope="col">HelioSure</th></tr></thead><tbody>'+
 [
 ['Purchase',money(EQUIPMENT.bargain_pv.cost),money(EQUIPMENT.premium_pv.cost)],
 ['Rated capacity','40 kW','50 kW'],
 ['Clear-noon output',solarEstimate('bargain_pv',s).peak.toFixed(1)+' kW',solarEstimate('premium_pv',s).peak.toFixed(1)+' kW'],
 ['Routine fault pressure','Standard','75% lower'],
 ['Unprepared hail damage','Higher','About half'],
 ['Footprint','2 × 2 tiles','2 × 2 tiles'],
 ['Best for','A smaller upfront budget','Output and reliability']
 ].map(row=>'<tr><th scope="row">'+row[0]+'</th><td>'+row[1]+'</td><td>'+row[2]+'</td></tr>').join('')+'</tbody></table><p class="mv-fine">Output assumes clean, healthy equipment on Sunny Meadow at full sunlight, with your completed research, before export limits. Fault comparison excludes the first tutorial fault.</p>';
 return heading('DEVELOP YOUR VALLEY','Choose the right equipment','An investment today. An operation to manage tomorrow.')+
 '<div class="mv-procure-layout"><nav class="mv-category" aria-label="Build categories">'+[['solar','Solar','sun'],['grid','Grid','power'],['facilities','Facilities','operations'],['landscape','Landscape','views']].map(([id,label,icon])=>action('category',glyph(icon)+'<span>'+label+'</span>',id,id===category?'selected':'','aria-pressed="'+(id===category)+'"')).join('')+'</nav>'+
 '<section class="mv-product-list" aria-label="Equipment options">'+items.map(id=>'<button class="mv-product '+(id===selected?'selected':'')+'" data-action="product" data-id="'+id+'" aria-pressed="'+(id===selected)+'"><img src="'+SITE_ICONS[id]+'" alt="'+esc(PRODUCT[id].short)+' model"><span class="mv-eyebrow">'+PRODUCT[id].tag+'</span><h3>'+PRODUCT[id].short+'</h3><p>'+PRODUCT[id].reason+'</p><footer><b>'+money(EQUIPMENT[id].cost)+'</b><span>'+ (EQUIPMENT[id].nameplateKw?EQUIPMENT[id].nameplateKw+' kW':id==='road'?'Per tile':'Per item')+'</span></footer></button>').join('')+'</section>'+
 '<section class="mv-product-detail"><div class="mv-preview"><img src="'+SITE_ICONS[selected]+'" alt="Preview of '+esc(p.short)+'"><span>'+d.footprint.x+' × '+d.footprint.y+' tiles</span></div>'+
 '<div class="mv-detail-title"><div><span class="mv-eyebrow">'+p.tag+'</span><h2>'+p.short+'</h2></div>'+tag(solar?(selected==='premium_pv'?'Reliability first':'Budget first'):'Site investment','mint')+'</div>'+
 '<p class="mv-lead">'+p.reason+'</p><p>'+p.tradeoff+'</p>'+
 (solar?'<div class="mv-tab-row">'+action('compare',compare?'Show overview':'Compare solar choices','','quiet','aria-pressed="'+compare+'"')+'</div>'+(compare?compareTable:'<div class="mv-stat-grid">'+stat('Rated capacity',d.nameplateKw+' kW')+stat('Clear-noon output',estimate.peak.toFixed(1)+' kW','Healthy, clean · Site A')+stat('Potential right now',estimate.potential.toFixed(1)+' kW','Before export limits')+stat('Available headroom',estimate.headroom.toFixed(1)+' kW','Across the current plant')+'</div>'+(estimate.clipped>0?'<div class="mv-callout amber">'+glyph('power')+'<span>At current sunlight, about '+estimate.clipped.toFixed(1)+' kW of the added potential would exceed export headroom. Consider an inverter.</span></div>':''))):'<div class="mv-callout">'+glyph('info')+'<span>'+esc(d.description)+'</span></div>')+
 '<details class="mv-facts"><summary>Good to know</summary><p>'+p.fact+'</p>'+(solar?'<p>Relative output factor: '+percent(d.efficiency)+' (a gameplay performance index, not physical cell-conversion efficiency). Base running cost: $'+estimate.runningCost.toFixed(2)+' per park hour. Wages and paid service are separate.</p><p>Equipment life is managed through condition and maintenance; this scenario has no fixed retirement age or warranty system.</p>':'')+'</details>'+
 '<footer class="mv-purchase"><div><small>Investment</small><strong>'+money(d.cost)+'</strong><span>'+ (s.cash>=d.cost?money(s.cash-d.cost)+' remains':money(d.cost-s.cash)+' short')+'</span></div>'+action('place','Place '+(solar?'array':p.short.toLowerCase())+' '+glyph('arrow'),selected,'primary',blocked?'disabled aria-label="'+esc(blocked)+'"':'')+'</footer>'+(blocked?'<p class="mv-blocked">'+glyph('lock')+blocked+'</p>':'')+'</section></div>';
}
export function people(s:GameSnapshot,selectedId:string|null,tab:string):string{
 const member=s.staff.find(m=>m.id===selectedId)??s.staff[0];
 const roster='<aside class="mv-roster"><div class="mv-section-label">YOUR TEAM <b>'+s.staff.length+'/5</b></div>'+s.staff.map(m=>'<button class="mv-person-row '+(m.id===member?.id?'selected':'')+'" data-action="person" data-id="'+m.id+'"><img src="'+PORTRAITS[m.role]+'" alt=""><span><b>'+esc(m.name)+'</b><small>'+ROLES[m.role].name+'</small><em>'+esc(taskLabel(m))+'</em></span></button>').join('')+action('staff-tab','Recruit someone','hire','quiet')+'</aside>';
 if(tab==='hire')return heading('PEOPLE MAKE THE POWER','Grow your team','Choose the role your operation needs next.')+'<div class="mv-people-layout">'+roster+'<section class="mv-hiring">'+Object.entries(ROLES).map(([id,r])=>'<article class="mv-hire-card"><img src="'+PORTRAITS[id as StaffMember['role']]+'" alt="'+r.name+' portrait"><h2>'+r.name+'</h2><p>'+r.description+'</p><small>'+money(id==='engineer'?2:1)+' salary / park hour</small>'+action('hire','Recruit · $1,500',id,'primary',s.staff.length>=5||s.cash<1500?'disabled':'')+'</article>').join('')+'</section></div>';
 if(!member)return heading('PEOPLE','Your team')+empty('No staff','Recruit a technician to begin.');
 const m=member,training=(m.trainingHoursLeft??0)>0;
 const tabs='<nav class="mv-tabs" aria-label="Staff profile">'+[['overview','Overview'],['assignment','Assignment'],['development','Development']].map(([id,label])=>action('staff-tab',label,id,tab===id?'selected':'quiet','aria-pressed="'+(tab===id)+'"')).join('')+'</nav>';
 let body='';
 if(tab==='assignment')body='<h3>Give '+esc(m.name.split(' ')[0])+' a focus</h3><p>Assignments apply after the current job finishes.</p><label class="mv-field">Work site<select data-field="zone"><option value="all" '+((m.workZone??'all')==='all'?'selected':'')+'>Both sites</option>'+s.plots.map(p=>'<option value="'+p.id+'" '+(m.workZone===p.id?'selected':'')+' '+(!p.unlocked?'disabled':'')+'>'+esc(p.id==='site_a'?'Sunny Meadow':'River Bench')+'</option>').join('')+'</select></label><label class="mv-field">Duty<select data-field="duty">'+[['auto','Suitable duties'],...(m.role!=='cleaner'?[['repair','Repair & service']]:[]),['clean','Panel cleaning'],...(m.role==='engineer'?[['research','Office research']]:[])].map(([id,label])=>'<option value="'+id+'" '+((m.preference??'auto')===id?'selected':'')+'>'+label+'</option>').join('')+'</select></label><div class="mv-callout">'+glyph('info')+'<span>'+ROLES[m.role].description+'</span></div>';
 else if(tab==='development')body='<h3>A little training goes a long way</h3><div class="mv-skill"><strong data-k="worker-skill">'+(m.skill??1).toFixed(1)+' / 5</strong><span>Field skill</span></div>'+meter((m.skill??1)/5,'Field skill')+'<p>Training raises skill by one. Four park hours at the office; current field work finishes first.</p>'+action('train',training?'Training · '+m.trainingHoursLeft!.toFixed(1)+' h left':'Book training · $800',m.id,'primary',training||(m.skill??1)>=5||s.cash<800?'disabled':'')+'<div class="mv-callout mint">'+glyph('research')+'<span>Higher skill speeds field work. An idle engineer also contributes more to research.</span></div>';
 else body='<div class="mv-task"><span class="mv-eyebrow">RIGHT NOW</span><h3>'+esc(taskLabel(m))+'</h3><p>'+esc(staffDestination(m,s))+'</p>'+(m.task.type!=='idle'?meter(m.task.progress,'Current task')+action('focus-asset','Find destination '+glyph('locate'),m.task.targetId,'quiet'):'')+'</div><div class="mv-stat-grid">'+stat('Field skill','<span data-k="worker-skill">'+(m.skill??1).toFixed(1)+' / 5</span>')+stat('Salary',money(m.salary??1),'/ park hour')+'</div><div class="mv-energy"><b>Energy</b><span>'+percent(m.energy??1)+'</span>'+meter(m.energy??1,'Energy')+'</div><div class="mv-trait"><span class="mv-eyebrow">PERSONALITY</span><h3>'+esc(m.trait??'Ready to help')+'</h3><p>'+traitText(m)+'</p></div>';
 return heading('YOUR PEOPLE',esc(m.name),ROLES[m.role].name+' · '+ROLES[m.role].specialty)+'<div class="mv-people-layout">'+roster+'<section class="mv-profile"><div class="mv-character"><span class="mv-character-halo"></span><img src="'+PORTRAITS[m.role]+'" alt="'+esc(m.name)+', '+ROLES[m.role].name+'"><div>'+tag(ROLES[m.role].name,'mint')+'<blockquote>“'+(m.trait==='Panel Whisperer'?'A clean panel is a happy panel.':m.role==='engineer'?'There is probably a better way.':'Let’s keep the valley running.')+'”</blockquote>'+action('focus-person',glyph('locate')+' Find in valley',m.id,'quiet')+'</div></div><div class="mv-profile-info">'+tabs+body+'<footer class="mv-profile-footer">'+action('staff-tab','Recruit staff','hire','quiet')+action('dismiss','Dismiss',m.id,'danger quiet')+'</footer></div></section></div>';
}
export function research(s:GameSnapshot,sim:GameSimulation,selected:ResearchId,tab:string):string{
 const tabs='<nav class="mv-tabs">'+action('research-tab','Engineering programmes','engineering',tab==='engineering'?'selected':'quiet')+action('research-tab','Company capabilities','capabilities',tab==='capabilities'?'selected':'quiet')+'</nav>';
 if(tab==='capabilities')return heading('MAKE THE COMPANY MORE CAPABLE','From hands-on to hands-off','Learn the job. Equip your team. Automate the repetition.')+tabs+'<div class="mv-capabilities">'+(Object.keys(CAPABILITY_INFO) as CapabilityId[]).map(id=>{
 const offer=capabilityOffer(id,s),done=s.capabilities.includes(id);
 return '<article class="mv-capability '+(done?'complete':'')+'">'+glyph(done?'check':'operations')+'<span class="mv-eyebrow">'+(done?'WORKING FOR YOU':'COMPANY CAPABILITY')+'</span><h2>'+CAPABILITY_INFO[id].name+'</h2><p>'+CAPABILITY_INFO[id].description+'</p>'+action('capability',offer.reason??(offer.cost?money(offer.cost):'Choose free upgrade'),id,done?'quiet':'primary',offer.reason?'disabled':'')+'</article>';
 }).join('')+'</div><div class="mv-future"><b>The management ladder</b><span>Manual work → Assigned staff → Policies → Automation → Manage exceptions</span></div>';
 const current=s.activeResearch,chosen=RESEARCH[selected],blocked=sim.researchBlockedReason(selected),support=researchSupport(s);
 return heading('INVEST IN WHAT COMES NEXT','Research & technology','Better equipment. More capable people. A more resilient company.')+
 '<div class="mv-research-top">'+tabs+'<span>'+s.researched.length+' / '+Object.keys(RESEARCH).length+' complete · Cash-funded programmes</span></div>'+
 (current?'<div class="mv-current-research">'+glyph('research')+'<div><span class="mv-eyebrow">IN PROGRESS</span><b>'+RESEARCH[current.id].name+'</b>'+meter(current.progress,'Research progress')+'</div><strong>'+percent(current.progress)+'</strong><span>~'+remainingResearch(s).toFixed(1)+' park h<br><small>At current staffing</small></span></div>':'<div class="mv-research-idle">'+glyph('research')+'<span>Choose one programme to fund. Your office progresses it over park time; available engineers can help.</span></div>')+
 '<div class="mv-research-layout"><div class="mv-tree" aria-label="Technology dependencies"><div class="mv-tiers"><span>FOUNDATIONS</span><span>DEVELOPMENT</span><span>ADVANCED</span></div>'+RESEARCH_BRANCHES.map(branch=>{
 const nodes=Object.entries(RESEARCH).filter(([,n])=>n.branch===branch.id);
 return '<section class="mv-branch"><header><h3>'+branch.name+'</h3><small>'+branch.subtitle+'</small></header><div class="mv-node-track">'+nodes.map(([id,node],i)=>{
 const done=s.researched.includes(id as ResearchId),active=current?.id===id,reason=sim.researchBlockedReason(id as ResearchId),state=done?'complete':active?'active':reason?'locked':'available';
 return (i?'<span class="mv-connector '+(done?'complete':'')+'" aria-label="requires '+esc(RESEARCH[node.prerequisite!].name)+'">'+glyph('arrow')+'</span>':'')+
 '<button class="mv-research-node '+state+' '+(id===selected?'selected':'')+'" data-action="research-select" data-id="'+id+'" data-research="'+id+'" aria-pressed="'+(id===selected)+'"><span class="mv-node-state">'+glyph(done?'check':active?'research':reason?'lock':'sun')+' '+(done?'Complete':active?'Researching':reason?'Locked':'Available')+'</span><h4>'+node.name+'</h4><small>'+money(node.cost)+' · '+node.hours+' h</small>'+(active?meter(current!.progress,'Project progress'):'')+'</button>';
 }).join('')+'</div></section>';
 }).join('')+'<div class="mv-future">'+glyph('lock')+'<div><b>Beyond the solar valley</b><span>Storage · Wind · Hybrid operations</span><small>Future campaign content — not purchasable in this scenario.</small></div></div></div>'+
 '<aside class="mv-research-detail"><span class="mv-eyebrow">'+chosen.branch.toUpperCase()+' PROGRAMME</span><h2>'+chosen.name+'</h2><p class="mv-lead">'+chosen.effect+'</p><p>'+chosen.description+'</p><div class="mv-stat-grid">'+stat('Investment',money(chosen.cost))+stat('Base duration',chosen.hours+' h','Park time')+'</div><h4>Prerequisite</h4><p>'+ (chosen.prerequisite?RESEARCH[chosen.prerequisite].name:'First programme in this branch')+'</p><h4>Engineering support</h4><p>'+ (support?'+'+percent(support)+' research rate from available engineers.':'The office researches at its base rate. An available engineer can accelerate it.')+'</p>'+action('research',blocked??'Fund programme',selected,'primary',blocked?'disabled':'')+(blocked?'<p class="mv-blocked">'+esc(blocked)+'</p>':'<small>'+money(s.cash-chosen.cost)+' cash after funding.</small>')+'</aside></div>';
}
