
import type {GameSnapshot} from '../../simulation/types';
import type {GameSimulation} from '../../simulation/GameSimulation';
import {EQUIPMENT} from '../../content/equipment';
import {CONTRACTS,contractOffer,type ContractId} from '../../content/contracts';
import {parkMetrics,hasServiceAccess,nearbyWorkshop,taskLabel} from '../../simulation/operations';
import {connectedRoads,roadKey} from '../../simulation/roads';
import {SITE_ICONS} from '../../game/siteArt';
import {PRODUCT} from './data';
import {esc,money,percent,action,glyph,heading,stat,meter,tag,empty} from './components';

export function inspector(s:GameSnapshot):string{
 const e=s.equipment.find(e=>e.id===s.selectedId);if(!e)return '';
 const d=EQUIPMENT[e.kind],p=PRODUCT[e.kind],pv=e.kind.includes('pv'),connected=connectedRoads(s.equipment).has(roadKey(e.tile));
 const pending=(kind:string)=>s.workOrders.some(o=>o.targetId===e.id&&o.kind===kind)||s.staff.some(m=>m.task.type!=='idle'&&m.task.targetId===e.id&&(m.task.type===kind||m.task.type==='travel'&&m.task.intent===kind));
 return heading(e.plotId==='site_a'?'SUNNY MEADOW':'RIVER BENCH',p.short)+
 '<div class="mv-inspector-body"><div class="mv-preview"><img src="'+SITE_ICONS[e.kind]+'" alt="'+p.short+'"></div>'+
 tag(!e.commissioned?'Under construction':e.faulted?'Fault · production stopped':'Operational',e.faulted?'red':'mint')+
 '<p>'+p.reason+'</p>'+(!e.commissioned?meter(e.constructionProgress,'Construction'):'')+
 (pv?'<div class="mv-stat-grid">'+stat('Rated capacity',d.nameplateKw+' kW')+stat('Condition',percent(e.condition))+'</div><h4>Cleanliness · '+percent(1-e.soiling)+'</h4>'+meter(1-e.soiling,'Cleanliness'):'')+
 '<div class="mv-callout"><span>'+(e.kind==='road'?(connected?'Connected access · nearby crew travel is 25% shorter.':'Isolated road. Join the main access route to improve travel.'):p.group==='landscape'?p.tradeoff:(hasServiceAccess(s.equipment,e)?'Road access · 25% shorter travel.':'Standard travel · no connected service road nearby.')+(nearbyWorkshop(s.equipment,e)?' Workshop in range: repairs finish one third sooner.':''))+'</span></div>'+
 (pv||e.kind==='inverter'?'<div class="mv-action-stack">'+action('repair',pending('repair')?'Repair assigned':'Send technician',e.id,'primary',!e.faulted||pending('repair')?'disabled':'')+(pv?action('clean',pending('clean')?'Cleaning assigned':'Order cleaning',e.id,'secondary',e.soiling<.15||!e.commissioned||pending('clean')?'disabled':'')+action('service',pending('service')?'Service assigned':'Service · $450',e.id,'secondary',!e.commissioned||e.faulted||e.condition>=.995||pending('service')?'disabled':''):'')+'</div>':'')+
 '<footer class="mv-action-stack">'+action('focus-asset',glyph('locate')+' Find in valley',e.id,'quiet')+(d.buildable?action('sell','Sell · '+money(Math.floor(d.cost*.6*e.condition)),e.id,'danger quiet'):'<small>Permanent infrastructure</small>')+'</footer></div>';
}
export function operations(s:GameSnapshot):string{
 const jobs=s.staff.filter(m=>m.task.type!=='idle'),name=(id:string)=>{const e=s.equipment.find(e=>e.id===id);return e?PRODUCT[e.kind].short+' · '+(e.plotId==='site_a'?'Sunny Meadow':'River Bench')+' ('+e.tile.x+', '+e.tile.y+')':'Equipment removed';};
 return heading('KEEP THE VALLEY RUNNING','Operations','Set the policy. Help the team with exceptions.')+'<div class="mv-management-grid"><section><h2>Routine care</h2>'+tag(s.capabilities.includes('radio_dispatch')?'Radio dispatch is active':'Manual fault dispatch','mint')+'<label class="mv-field">Automatic cleaning threshold<select data-field="cleaning" '+(!s.capabilities.includes('scheduled_cleaning')?'disabled':'')+'>'+[.2,.35,.5].map(n=>'<option value="'+n+'" '+(s.cleaningThreshold===n?'selected':'')+'>'+percent(n)+' dust</option>').join('')+'</select></label><p>'+ (s.capabilities.includes('scheduled_cleaning')?'Suitable staff receive cleaning orders automatically.':'Requires Scheduled Cleaning from Company capabilities.')+'</p><label class="mv-field mv-checkbox"><input type="checkbox" data-field="preventive" '+(s.preventiveMaintenance?'checked':'')+' '+(!s.researched.includes('predictive_diagnostics')?'disabled':'')+'> Automatic preventive service</label><p>Predictive Diagnostics unlocks this policy. Each service costs $450; automation preserves a $1,500 reserve.</p><div class="mv-action-stack">'+action('clean-all','Queue dirty arrays')+action('service-all','Queue worn arrays')+action('page','Explore capabilities','research','quiet')+'</div></section><section><h2>Field work <small>'+jobs.length+' active · '+s.workOrders.length+' waiting</small></h2>'+jobs.map(m=>'<article class="mv-job"><div><b>'+esc(m.name)+'</b><p>'+taskLabel(m)+' · '+(m.task.type!=='idle'?name(m.task.targetId):'')+'</p></div>'+action('person','Profile',m.id,'quiet')+'</article>').join('')+s.workOrders.map(o=>'<article class="mv-job"><div><b>'+o.kind.toUpperCase()+'</b><p>'+name(o.targetId)+'</p><small>'+(o.manual?'Requested by you':'Company policy')+'</small></div>'+action('locate','Find',o.targetId,'quiet')+action('cancel-job','Cancel',o.targetId,'quiet','data-kind="'+o.kind+'"')+'</article>').join('')+(!jobs.length&&!s.workOrders.length?empty('All caught up','Select an array in the valley to arrange a job.'):'')+'</section></div>';
}
export function company(s:GameSnapshot,sim:GameSimulation,tab:string):string{
 const m=parkMetrics(s.equipment),a=s.contract;
 const tabs='<nav class="mv-tabs">'+action('company-tab','Finances','finance',tab==='finance'?'selected':'quiet')+action('company-tab','Supply contracts','contracts',tab==='contracts'?'selected':'quiet')+'</nav>';
 if(tab==='contracts')return heading('COMMERCIAL','Power with a purpose','Optional supply challenges. Ordinary electricity sales continue.')+tabs+
 (a?'<section class="mv-contract-active"><span class="mv-eyebrow">ACTIVE DELIVERY</span><h2>'+esc(a.title)+'</h2>'+meter(a.deliveredKwh/a.energyKwh,'Delivery')+'<p>'+Math.round(a.deliveredKwh)+' / '+a.energyKwh+' kWh · '+Math.max(0,a.hours-a.elapsedHours).toFixed(1)+' park hours remaining</p>'+action('cancel-contract','Cancel · forfeit '+money(a.deposit),'','danger quiet')+'</section>':'')+
 '<div class="mv-contracts">'+(Object.keys(CONTRACTS) as ContractId[]).map(id=>{const o=contractOffer(id,s.contractRenewals),reason=sim.contractBlockedReason(id);return '<article><span class="mv-eyebrow">SUPPLY AGREEMENT</span><h2>'+o.title+'</h2><p>'+o.description+'</p>'+stat('Deliver',o.energyKwh.toLocaleString()+' kWh','Within '+o.hours+' park hours')+stat('Completion bonus',money(o.reward),money(o.deposit)+' deposit')+'<p>Availability '+percent(o.minimumAvailability)+' · Condition '+percent(o.minimumCondition)+'</p>'+action('contract',reason??'Accept agreement',id,'primary',reason?'disabled':'')+'</article>';}).join('')+'</div>';
 return heading('YOUR COMPANY','Follow the money','Understand today before investing in tomorrow.')+tabs+'<div class="mv-finance-stats">'+stat('Available cash',money(s.cash))+stat('Current net',money(s.revenuePerHour),'/ park hour')+stat('Export',s.exportedKw.toFixed(1)+' kW',s.inverterCapacityKw.toFixed(0)+' kW connection')+stat('Availability',percent(m.availability))+'</div><div class="mv-management-grid"><section><h2>Today’s ledger</h2>'+[['Electricity sold',Math.round(s.currentReport.energyKwh)+' kWh'],['Electricity revenue',money(s.currentReport.revenue)],['Operating expenses',money(s.currentReport.expenses)],['Bonuses',money(s.currentReport.bonuses)],['Lifetime sales',money(s.lifetimeRevenue)]].map(([k,v])=>'<div class="mv-ledger"><span>'+k+'</span><b>'+v+'</b></div>').join('')+'<p>Operating expenses include wages, running equipment and service. Capital purchases and research are separate.</p></section><section><h2>Export headroom</h2>'+meter(s.exportedKw/s.inverterCapacityKw,'Export capacity')+'<p>'+(s.clippedKw>0?s.clippedKw.toFixed(1)+' kW is currently curtailed by your connection. More inverter capacity lets you sell more.':'Your connection has room for current generation. Compare clear-noon output before expanding.')+'</p>'+action('category','Compare grid equipment','grid')+'<h3>Recent days</h3>'+s.dailyReports.slice(-5).reverse().map(r=>'<div class="mv-ledger"><span>Day '+r.day+'</span><b>'+money(r.revenue-r.expenses)+' net</b></div>').join('')+'</section></div>';
}
export function objectives(s:GameSnapshot):string{
 return heading('HERE COMES THE SUN','Your valley, your ambition','One star opens the next chapter. Stay for mastery.')+'<div class="mv-awards">'+'★'.repeat(s.stars)+'☆'.repeat(3-s.stars)+'</div><div class="mv-objective-list">'+s.objectives.map(o=>'<article class="'+(o.complete?'complete':o.active?'active':'')+'">'+glyph(o.complete?'check':o.active?'objectives':'lock')+'<div><h3>'+esc(o.title)+'</h3><p>'+esc(o.description)+'</p><small>'+esc(o.rewardText??'')+'</small></div></article>').join('')+'</div><p class="mv-fine">Scenario 2 is unlocked by your first star. It is planned for a future campaign release and is not yet playable.</p>';
}
