import type { EquipmentDef, EquipmentKind } from '../simulation/types';

export const EQUIPMENT: Record<EquipmentKind, EquipmentDef> = {
  bargain_pv: {
    id: 'bargain_pv',
    name: 'Bargain PV Array',
    description: 'Cheaper panels. Weaker output and more faults.',
    cost: 8000,
    footprint: { x: 2, y: 2 },
    nameplateKw: 40,
    reliability: 0.72,
    efficiency: 0.85,
    buildable: true,
    category: 'generation',
  },
  premium_pv: {
    id: 'premium_pv',
    name: 'Premium PV Array',
    description: 'Costlier panels. Stronger output and higher reliability.',
    cost: 14000,
    footprint: { x: 2, y: 2 },
    nameplateKw: 50,
    reliability: 0.93,
    efficiency: 1,
    buildable: true,
    category: 'generation',
  },
  inverter: {
    id: 'inverter',
    name: 'String Inverter',
    description: 'Converts DC to AC for grid export. Needed beyond the starter link.',
    cost: 6000,
    footprint: { x: 1, y: 1 },
    nameplateKw: 200,
    reliability: 0.95,
    efficiency: 0.97,
    buildable: true,
    category: 'electrical',
  },
  office: {
    id: 'office',
    name: 'Ops Office',
    description: 'Tiny operations hut.',
    cost: 0,
    footprint: { x: 2, y: 2 },
    nameplateKw: 0,
    reliability: 1,
    efficiency: 1,
    buildable: false,
    category: 'building',
  },
  substation: {
    id: 'substation',
    name: 'Grid Connection',
    description: 'Local export point.',
    cost: 0,
    footprint: { x: 2, y: 2 },
    nameplateKw: 250,
    reliability: 1,
    efficiency: 1,
    buildable: false,
    category: 'electrical',
  },
};

export const BUILD_MENU_ORDER: EquipmentKind[] = ['bargain_pv', 'premium_pv', 'inverter'];
