import { chromium } from 'playwright';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
await mkdir('browser-evidence',{recursive:true});
const browser = await chromium.launch({channel:'chrome',headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context = await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true});
const page = await context.newPage();
const errors = [];
page.on('pageerror',(error)=>errors.push(error.message));
page.on('console',(message)=>{if(message.type()==='error')errors.push(message.text());});
page.on('request',(request)=>{if(/^https?:/.test(request.url()))errors.push('Unexpected network dependency: '+request.url());});
page.on('dialog',(dialog)=>dialog.accept());
const url = pathToFileURL(path.resolve('playable/PLAY-MEGAWATT-VALLEY.html')).href;
await page.goto(url);
await page.locator('[data-action="save"]').waitFor({timeout:60000});
await page.locator('[data-speed="0"]').click();
async function saved() {
  await page.locator('[data-action="save"]').click();
  return page.evaluate(()=>JSON.parse(localStorage.getItem('megawatt-valley-solar-v1')).state);
}
const before = await saved();
assert.ok(Math.abs(before.cash - 50000) < 20);
assert.equal(before.equipment.length,3);
assert.equal(await page.locator('#game-root canvas').count(),1);
assert.equal(await page.locator('img').evaluateAll((images)=>images.every((img)=>img.complete && img.naturalWidth>0)),true);
await page.screenshot({path:'browser-evidence/opening.png'});
console.log('OPENING_BASE64:'+(await page.screenshot({type:'jpeg',quality:40})).toString('base64'));
const cleanStyle=await page.addStyleTag({content:'#ui-root { visibility: hidden !important; }'});
await page.screenshot({path:'browser-evidence/valley-overview.png'});
console.log('VALLEY_BASE64:'+(await page.screenshot({type:'jpeg',quality:75})).toString('base64'));
await cleanStyle.evaluate(el=>el.remove());
await page.locator('[data-cat="support"]').click();
assert.equal(await page.locator('[data-build="workshop"]').isDisabled(),true);
await page.locator('[data-cat="generation"]').click();
await page.locator('[data-build="bargain_pv"]').click();
await page.mouse.move(910,520);
await page.screenshot({path:'browser-evidence/placement-feedback.png'});
await page.locator('[data-action="cancel-build"]').click();
let built = false;
for(const point of [{x:450,y:320},{x:550,y:320},{x:650,y:320},{x:750,y:320},{x:450,y:420},{x:550,y:420},{x:650,y:420},{x:750,y:420},{x:850,y:420},{x:550,y:520},{x:650,y:520}]) {
  await page.locator('[data-build="bargain_pv"]').click();
  await page.mouse.click(point.x,point.y);
  const state = await saved();
  if(state.equipment.length>3){assert.equal(state.cash,before.cash-8000);built=true;break;}
}
assert.ok(built,'A player can place PV through canvas input');
await page.locator('[data-action="cancel-build"]').click();
await page.reload();
await page.locator('[data-action="save"]').waitFor({timeout:60000});
const resumed = await saved();
assert.equal(resumed.equipment.length,4); assert.equal(resumed.cash,before.cash-8000);
await page.locator('[data-action="jump"][data-id="people"]').click();
await page.locator('[data-action="hire"][data-id="cleaner"]').click();
assert.equal((await saved()).staff.length,2);
await page.locator('[data-action="new"]').click();
assert.equal((await saved()).equipment.length,3);
await page.locator('[data-action="new"]').click();
await page.locator('[data-action="hire"][data-id="cleaner"]').scrollIntoViewIfNeeded();
await page.locator('[data-action="hire"][data-id="cleaner"]').click();
assert.equal((await saved()).staff.length,2);
await page.locator('[data-action="export-save"]').click();
async function importFixture(name) {
  const chooser = page.waitForEvent('filechooser');
  await page.locator('[data-action="import-save"]').click();
  await (await chooser).setFiles('browser-fixtures/'+name+'.json');
  await page.waitForTimeout(300);
}
await importFixture('storm');
await page.locator('[data-action="event-choice"][data-id="prepare"]').waitFor();
await page.locator('[data-action="event-choice"][data-id="prepare"]').click();
assert.equal((await saved()).hailPrepared,true);
await importFixture('one-star');
await page.locator('[data-k="win"]:not([hidden])').waitFor();
await page.locator('[data-action="dismiss-win"]').click();
assert.ok((await saved()).stars>=1);
await page.screenshot({path:'browser-evidence/one-star.png'});
console.log('COMPLETION_BASE64:'+(await page.screenshot({type:'jpeg',quality:40})).toString('base64'));
const detailStyle=await page.addStyleTag({content:'#ui-root { visibility: hidden !important; }'});
await page.mouse.move(700,420);await page.mouse.wheel(0,-170);await page.waitForTimeout(300);
await page.screenshot({path:'browser-evidence/infrastructure-detail.png'});
console.log('DETAIL_BASE64:'+(await page.screenshot({type:'jpeg',quality:75})).toString('base64'));
await page.mouse.wheel(0,170);await page.waitForTimeout(300);
await detailStyle.evaluate(el=>el.remove());
// Render-only lighting fixture. Economic completion above still uses normal time.
const night=JSON.parse(await readFile('browser-fixtures/one-star.json','utf8'));
night.state.hour=22;night.state.speed=0;night.state.weather='clear';
await writeFile('browser-fixtures/night.json',JSON.stringify(night));
await importFixture('night');
assert.equal((await saved()).hour,22);
const nightStyle=await page.addStyleTag({content:'#ui-root { visibility: hidden !important; }'});
await page.mouse.move(700,420);await page.mouse.wheel(0,-170);await page.waitForTimeout(300);
await page.screenshot({path:'browser-evidence/evening-lights.png'});
console.log('NIGHT_BASE64:'+(await page.screenshot({type:'jpeg',quality:75})).toString('base64'));
await page.mouse.wheel(0,170);await page.waitForTimeout(300);
await nightStyle.evaluate(el=>el.remove());
await importFixture('one-star');
await page.setViewportSize({width:1024,height:768});
await page.locator('[data-action="capability"][data-id="cleaning_rig"]').scrollIntoViewIfNeeded();
assert.ok(await page.locator('[data-action="capability"][data-id="cleaning_rig"]').isVisible());
await page.screenshot({path:'browser-evidence/laptop.png'});
assert.deepEqual(errors,[]);
console.log('BROWSER_CHECK_PASSED: offline launch, assets, placement, reload, hiring, restart, laptop capability access');
const jpeg = await page.screenshot({type:'jpeg',quality:45});
console.log('SCREENSHOT_BASE64:'+jpeg.toString('base64'));
await browser.close();
