import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
await mkdir('three-evidence',{recursive:true});
const browser=await chromium.launch({channel:'chrome',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto(pathToFileURL(path.resolve('playable/PLAY-MEGAWATT-VALLEY.html')).href);
await page.locator('[data-k="tycoon-ui"]').waitFor({timeout:90000});
await page.locator('[data-action="speed"][data-id="0"]').click();await page.waitForTimeout(500);
const paused=await page.evaluate(()=>window.megawattRenderInfo().activity);
await page.waitForTimeout(600);
assert.deepEqual(await page.evaluate(()=>window.megawattRenderInfo().activity),paused,'Paused companies also pause world activity');
await page.locator('[data-action="speed"][data-id="1"]').click();await page.waitForTimeout(1400);
await page.locator('[data-action="speed"][data-id="0"]').click();
const active=await page.evaluate(()=>window.megawattRenderInfo().activity);
assert.notDeepEqual(active.traffic,paused.traffic,'Traffic moves along the public road');
assert.notDeepEqual(active.ducks,paused.ducks,'River wildlife animates');
console.log('ACTIVITY_CHECK_PASSED: traffic and ducks advance only during play');
console.log('RENDER_INFO:'+JSON.stringify(await page.evaluate(()=>window.megawattRenderInfo())));
await page.screenshot({path:'three-evidence/3d-first-company.png'});
console.log('THREE_DEFAULT_BASE64:'+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'));
await page.addStyleTag({content:'#ui-root{visibility:hidden!important}'});
await page.screenshot({path:'three-evidence/3d-valley.png'});
console.log('THREE_WORLD_BASE64:'+(await page.screenshot({type:'jpeg',quality:70})).toString('base64'));
await page.mouse.move(650,420);await page.mouse.wheel(0,-230);await page.waitForTimeout(300);
await page.screenshot({path:'three-evidence/3d-closeup.png'});
console.log('THREE_DETAIL_BASE64:'+(await page.screenshot({type:'jpeg',quality:70})).toString('base64'));
// Inspect real starter assets at working distance, with the same in-game camera controls.
await page.keyboard.press('h');
await page.mouse.click(478,190);await page.keyboard.press('f');
await page.mouse.move(720,450);await page.mouse.wheel(0,-620);await page.waitForTimeout(350);
await page.screenshot({path:'three-evidence/campus-office-detail.png'});
console.log('CAMPUS_OFFICE_BASE64:'+(await page.screenshot({type:'jpeg',quality:80})).toString('base64'));
await page.keyboard.press('h');
await page.mouse.click(633,343);await page.keyboard.press('f');
await page.mouse.move(720,450);await page.mouse.wheel(0,-620);await page.waitForTimeout(350);
await page.screenshot({path:'three-evidence/campus-solar-detail.png'});
console.log('CAMPUS_SOLAR_BASE64:'+(await page.screenshot({type:'jpeg',quality:80})).toString('base64'));
const timing=await page.evaluate(async()=>{
 const frames=[];let previous=performance.now();
 for(let i=0;i<30;i++){const now=await new Promise(resolve=>requestAnimationFrame(resolve));frames.push(now-previous);previous=now;}
 frames.sort((a,b)=>a-b);
 return {sampleFrames:frames.length,medianMs:frames[15],p95Ms:frames[28],userAgent:navigator.userAgent,logicalCores:navigator.hardwareConcurrency,viewport:[innerWidth,innerHeight],render:window.megawattRenderInfo()};
});
console.log('CAMPUS_PERFORMANCE_DIAGNOSTIC:'+JSON.stringify({backend:'CI Chrome SwiftShader software rendering; not a player GPU benchmark',...timing}));
await browser.close();
if(errors.length)throw new Error(errors.join('\n'));
