import {chromium} from 'playwright';
import {mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
await mkdir('three-evidence',{recursive:true});
const browser=await chromium.launch({channel:'chrome',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900}});
page.on('pageerror',e=>console.log('PAGE_ERROR:'+e.message));
page.on('console',m=>{if(m.type()==='error')console.log('RENDER_ERROR:'+m.text());});
await page.goto(pathToFileURL(path.resolve('playable/PLAY-MEGAWATT-VALLEY.html')).href);
await page.locator('[data-k="management-dock"]').waitFor({timeout:90000});
await page.locator('[data-speed="0"]').click();await page.waitForTimeout(500);
console.log('RENDER_INFO:'+JSON.stringify(await page.evaluate(()=>window.megawattRenderInfo())));
await page.screenshot({path:'three-evidence/3d-first-company.png'});
console.log('THREE_DEFAULT_BASE64:'+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'));
await page.addStyleTag({content:'#ui-root{visibility:hidden!important}'});
await page.screenshot({path:'three-evidence/3d-valley.png'});
console.log('THREE_WORLD_BASE64:'+(await page.screenshot({type:'jpeg',quality:70})).toString('base64'));
await page.mouse.move(650,420);await page.mouse.wheel(0,-230);await page.waitForTimeout(300);
await page.screenshot({path:'three-evidence/3d-closeup.png'});
console.log('THREE_DETAIL_BASE64:'+(await page.screenshot({type:'jpeg',quality:70})).toString('base64'));
await browser.close();
